name: Deploy to Github Pages

on:
  push:
  schedule:
    - cron: "*/28 * * * *" # every 30 min

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      # Uncomment if you want to specify a certain
      # Node version. Otherwise the Node version installed
      # on the GitHub VM will be used. For more details
      # see: https://github.com/actions/virtual-environments
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "16.7.0"

      # Uncomment if your project uses dependencies
      - name: Install dependencies
        run: npm ci

      - name: Build the website
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: main # default: gh-pages
          publish_dir: ./public
          external_repository: jr-b/jr-b.github.io
          keep_files: true
