name: Deploy to Github Pages

on:
  push:
  schedule:
  - cron:  '*/30 * * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      # Uncomment if you want to specify a certain 
      # Node version. Otherwise the Node version installed
      # on the GitHub VM will be used. For more details
      # see: https://github.com/actions/virtual-environments 
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4 
        with:
          node-version: '16.7.0'

      # Uncomment if your project uses dependencies
      - name: Install dependencies
        run: npm ci

      - name: Build the website
        run: npm run build
    
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GHPAGES_TOKEN }}   
          publish_branch: main  # default: gh-pages       
          publish_dir: ./public
          external_repository: jr-b/jr-b.github.io
          keep_files: true



      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2 # replace this with your aws-region

      # - name: Upload files to S3 with AWS CLI
      #   run: |
      #     aws s3 sync public/ s3://${{ secrets.S3_BUCKET }}
          
#      - name: Invalidate CloudFront cache for all paths
#        run: |
#          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"
